# Site
repository: YiyuanLei/yiyuanlei.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Oliver Lei
title: PhD Candidate at NYU
email: yl6549@nyu.edu
website: yiyuanlei.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: Yiyuan Lei
#github_username:  YiyuanLei
instagram_username: yiyuanlei
linkedin_username: yiyuanlei
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I am a graduate research assitant at New York University. I obtained my master degree in Statistics and Civil Engineering from the University of Illinois at Urbana-Champaign. My research is about proactive traffic safety evaluation and management. 
  I am interested in <mark>Causal Inference</mark>, <mark>Statistical Learning</mark> and <mark>Stochastic Process</mark>. 
  Please see my [Google scholar profile](https://scholar.google.com/citations?user=-pXDUYYAAAAJ&hl=en&oi=ao) for my publications.
content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Public policy evaluation
        sub_title: Causal Inference
        # link:
        # link_text: Project Website
  
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
   
        description: | # this will include new lines to allow paragraphs
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Uber Tech Inc
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Applied Scientist PhD Intern
        caption: 05/2022 - 08/2022
        description: | # this will include new lines to allow paragraphs
            Proactive retention strategies using machine learning models
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New York University
        caption: 2019 - 2023
        sub_title: PhD in Transportation Engineering
        description: | # this will include new lines to allow paragraphs
           <br /> GPA: 3.85.
           <br /> Selecte Courses: Causal Inference, Adv Topics in Numerical Analysis: Monte Carlo Sampling Methods, Forecasting Time Series Data, Advanced Mache Learning, Adv Topics in Survival Analysis, System Optimization Method, Stochastic Models and Methods, Data-driven mobility modeling,
  - title: Blogs
    layout: text
    content: | # this will include new lines to allow paragraphs
      More to come
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
